### ISSUE TITLE
Utilisation d'un CMS

### ISSUE THREAD

**Issue by laem** [betagouv/beta.gouv.fr#1349]
Comme évoqué la semaine dernière sur Slack, j'ai testé Netlify. C'est un CMS pour sites statiques libre et une entreprise derrière qui se fait de l'argent en l'hébergeant. 

**Je pense que ça peut être une solution pour mieux accueillir les contributions de contenu, qui sont aujourd'hui loin d'êtres faciles**. 

Le CMS permet de créer du contenu dans une interface WYSIWYG, tout en restant complètement sur Github et un site statique.

En images !

Les dev spécifient les entités qui peuvent être créées : 

```yaml

collections:
  - name: "startup"
    label: "Startup"
    folder: "src/pages/startup"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Mission", name: "mission", widget: "string"}
      - {label: "Création", name: "création", widget: "datetime"}
      - {label: "Fiche produit", name: "ficheProduit", widget: "markdown"}
      - {label: 'Statut', name: "statut", widget: "select", options: ["investigation", "consolidation", "passation"]}
      - {label: 'Image', name: 'image', widget: 'image'}
      
  - name: "blog"
# ... et ainsi de suite

```

Cette spec produit une page "Startups" dans l'interface d'admin qui propose d'en crééer une avec un formulaire.
![](http://i.imgur.com/f6bEPP1.jpg)

Vous voyez l'attribut `widget` dans le code YAML : ça permet de proposer des étapes du formulaire complètement personnalisées, par exemple la carte qui est en train d'être développée pour afficher l'adresse des incubateurs.

Une fois rempli le contenu passe en phase Draft du workflow, puis Review, puis Ready. Toute modification est reflétée sur une PR github : on peut donc discuter dessus comme aujourd'hui. Exemple [ici](https://github.com/laem/btgv/pull/2). Chaque modification donne lieu à un nouveau commit par l'utilisateur qui a fait les modifications dans le formulaire.

![](http://i.imgur.com/vRlklyC.jpg)

Le contenu est stocké sur le dépôt Github comme aujourd'hui, et un site statique livre tout ça sur beta.gouv.fr.
