### ISSUE TITLE
Un membre est passé en alumni alors qu'il a toujours une mission en cours

### ISSUE THREAD

**Issue by SebastienReuiller** [betagouv/beta.gouv.fr#20839]
La mise à jour de la date de fin de ma mission a bien été mise à jour, mais j'apparais toujours en Alumni sur https://beta.gouv.fr/communaute/annuaire

Je pense que c'est du au fait que j'ai eu une mission en parallèle et que par conséquent, la mission en cours n'est pas la dernière dans la définition : 

```
missions:
  - start: 2023-06-26
    end: 2025-04-30
    status: independent
    employer: Malt
    startups:
      - place-de-marche-inclusion
  - start: 2024-01-01
    end: 2024-09-30
    status: independent
    employer: LBC
    startups:
      - recommandations-collaboratives
      - urbanvitaliz
 ```

La fiche : https://raw.githubusercontent.com/betagouv/beta.gouv.fr/refs/heads/master/content/_authors/sebastien.reuiller.md
